INSERT INTO DEPARTMENT (ID, name) VALUES (1, 'IT');
INSERT INTO DEPARTMENT (ID, name) VALUES (2, 'Operations');
INSERT INTO DEPARTMENT (ID, name) VALUES (3, 'Finance');
INSERT INTO DEPARTMENT (ID, name) VALUES (4, 'Sales');
INSERT INTO DEPARTMENT (ID, name) VALUES (5, 'Human Resource');
INSERT INTO DEPARTMENT (ID, name) VALUES (6, 'Purchase ');