INSERT INTO EMPLOYEE (ID, NAME, PHONE, EMAIL, PROVINCE_CODE, DISTRICT_CODE, WARD_CODE,
                      POSITION, DEPARTMENTID, MANAGERID)
VALUES (1, 'Nguyen Van A', '0974442311',
        'NguyenVanA@gmail.com', '01', '001', '00001', 'Manager', 1, null);

INSERT INTO EMPLOYEE (ID, NAME, PHONE, EMAIL, PROVINCE_CODE, DISTRICT_CODE, WARD_CODE,
                      POSITION, DEPARTMENTID, MANAGERID)
VALUES (2, 'Nguyen Van B', '0974442311',
        'NguyenVanB@gmail.com', '01', '001', '00001', 'Leader', 1, 1);

INSERT INTO EMPLOYEE (ID, NAME, PHONE, EMAIL, PROVINCE_CODE, DISTRICT_CODE, WARD_CODE,
                      POSITION, DEPARTMENTID, MANAGERID)
VALUES (3, 'Nguyen Van C', '0974442311',
        'NguyenVanC@gmail.com', '01', '001', '00001', 'Leader', 1, 1);
